
import type { Metadata } from "next";
// @ts-ignore: allow side-effect import of CSS without type declarations
import "./globals.css";

import AppShell from "./AppShell";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased bg-black text-white dark">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}